[package]
name = "yew_hello"
version = "0.1.0"
edition = "2024"

[dependencies]
yew = { version = "0.21"}
wasm-bindgen = "0.2"

[lib]
crate-type = ["cdylib"]

[dependencies.web-sys]
version = "0.3"
features = ["Window"]
